### ISSUE TITLE
SHIFT & click to append selection to file

### ISSUE THREAD

**Issue by Sony-1972** [alexofrhodes/AHK-Snippet-Manager#1]
this feature is not working for me

**Comment by alexofrhodes** [comment]
Hello, thanks for reaching out. I just tested it and it works. 
Can you confirm the following:
- You have a file you want to append to
- select the new text somewhere
- enable the popup menu and navigate to the file you want to append
- keep SHIFT pressed while you Click on that file.

**Comment by pgeugene** [comment]
Hi.
Thank you for your fast reply.
Your script is working properly from the beginning.
It was my mistake.
Today I found out that I have another script which contain the same Hotkey (+LButton) that trigger another ahk script which interfered with your script feature
Finally thank you for your great script

**Comment by alexofrhodes** [comment]
I'm very glad you like it!
